function CodeDefine() { 
this.def = new Array();
this.def["IsrOverrun"] = {file: "ert_main_c.html",line:23,type:"var"};
this.def["isRateRunning"] = {file: "ert_main_c.html",line:24,type:"var"};
this.def["need2runFlags"] = {file: "ert_main_c.html",line:26,type:"var"};
this.def["rt_OneStep"] = {file: "ert_main_c.html",line:28,type:"fcn"};
this.def["stopRequested"] = {file: "ert_main_c.html",line:111,type:"var"};
this.def["main"] = {file: "ert_main_c.html",line:112,type:"fcn"};
this.def["ArduinoTest_DW"] = {file: "ArduinoTest_c.html",line:24,type:"var"};
this.def["ArduinoTest_M_"] = {file: "ArduinoTest_c.html",line:27,type:"var"};
this.def["ArduinoTest_M"] = {file: "ArduinoTest_c.html",line:28,type:"var"};
this.def["ArduinoTest_SetEventsForThisBaseStep"] = {file: "ArduinoTest_c.html",line:43,type:"fcn"};
this.def["ArduinoTest.c:rate_monotonic_scheduler"] = {file: "ArduinoTest_c.html",line:57,type:"fcn"};
this.def["ArduinoTest.c:matlabCodegenHandle_matlabCodeg"] = {file: "ArduinoTest_c.html",line:69,type:"fcn"};
this.def["ArduinoTest.c:matlabCodegenHandle_matlabCo_ky"] = {file: "ArduinoTest_c.html",line:76,type:"fcn"};
this.def["ArduinoTest.c:arduino_AnalogInput_set_pinNumb"] = {file: "ArduinoTest_c.html",line:83,type:"fcn"};
this.def["ArduinoTest_step0"] = {file: "ArduinoTest_c.html",line:106,type:"fcn"};
this.def["ArduinoTest_step1"] = {file: "ArduinoTest_c.html",line:213,type:"fcn"};
this.def["ArduinoTest_initialize"] = {file: "ArduinoTest_c.html",line:255,type:"fcn"};
this.def["ArduinoTest_terminate"] = {file: "ArduinoTest_c.html",line:360,type:"fcn"};
this.def["DW_ArduinoTest_T"] = {file: "ArduinoTest_h.html",line:71,type:"type"};
this.def["codertarget_arduinobase_block_T"] = {file: "ArduinoTest_types_h.html",line:34,type:"type"};
this.def["c_cell_ArduinoTest_T"] = {file: "ArduinoTest_types_h.html",line:54,type:"type"};
this.def["e_codertarget_arduinobase_int_T"] = {file: "ArduinoTest_types_h.html",line:63,type:"type"};
this.def["codertarget_arduinobase_inter_T"] = {file: "ArduinoTest_types_h.html",line:77,type:"type"};
this.def["P_ArduinoTest_T"] = {file: "ArduinoTest_types_h.html",line:82,type:"type"};
this.def["RT_MODEL_ArduinoTest_T"] = {file: "ArduinoTest_types_h.html",line:85,type:"type"};
this.def["ArduinoTest_P"] = {file: "ArduinoTest_data_c.html",line:24,type:"var"};
this.def["int8_T"] = {file: "rtwtypes_h.html",line:51,type:"type"};
this.def["uint8_T"] = {file: "rtwtypes_h.html",line:52,type:"type"};
this.def["int16_T"] = {file: "rtwtypes_h.html",line:53,type:"type"};
this.def["uint16_T"] = {file: "rtwtypes_h.html",line:54,type:"type"};
this.def["int32_T"] = {file: "rtwtypes_h.html",line:55,type:"type"};
this.def["uint32_T"] = {file: "rtwtypes_h.html",line:56,type:"type"};
this.def["real32_T"] = {file: "rtwtypes_h.html",line:57,type:"type"};
this.def["real64_T"] = {file: "rtwtypes_h.html",line:58,type:"type"};
this.def["real_T"] = {file: "rtwtypes_h.html",line:64,type:"type"};
this.def["time_T"] = {file: "rtwtypes_h.html",line:65,type:"type"};
this.def["boolean_T"] = {file: "rtwtypes_h.html",line:66,type:"type"};
this.def["int_T"] = {file: "rtwtypes_h.html",line:67,type:"type"};
this.def["uint_T"] = {file: "rtwtypes_h.html",line:68,type:"type"};
this.def["ulong_T"] = {file: "rtwtypes_h.html",line:69,type:"type"};
this.def["char_T"] = {file: "rtwtypes_h.html",line:70,type:"type"};
this.def["uchar_T"] = {file: "rtwtypes_h.html",line:71,type:"type"};
this.def["byte_T"] = {file: "rtwtypes_h.html",line:72,type:"type"};
this.def["creal32_T"] = {file: "rtwtypes_h.html",line:82,type:"type"};
this.def["creal64_T"] = {file: "rtwtypes_h.html",line:87,type:"type"};
this.def["creal_T"] = {file: "rtwtypes_h.html",line:92,type:"type"};
this.def["cint8_T"] = {file: "rtwtypes_h.html",line:99,type:"type"};
this.def["cuint8_T"] = {file: "rtwtypes_h.html",line:106,type:"type"};
this.def["cint16_T"] = {file: "rtwtypes_h.html",line:113,type:"type"};
this.def["cuint16_T"] = {file: "rtwtypes_h.html",line:120,type:"type"};
this.def["cint32_T"] = {file: "rtwtypes_h.html",line:127,type:"type"};
this.def["cuint32_T"] = {file: "rtwtypes_h.html",line:134,type:"type"};
this.def["pointer_T"] = {file: "rtwtypes_h.html",line:152,type:"type"};
this.def["MW_AnalogIn_TriggerSource_Type"] = {file: "MW_AnalogIn_h.html",line:15,type:"type"};
this.def["MW_AnalogIn_Status_Type"] = {file: "MW_AnalogIn_h.html",line:22,type:"type"};
this.def["MW_AnalogIn_ResultDataType_Type"] = {file: "MW_AnalogIn_h.html",line:33,type:"type"};
this.def["MW_AnalogInSingle_Open"] = {file: "MW_AnalogInput_cpp.html",line:14,type:"fcn"};
this.def["MW_AnalogIn_SetTriggerSource"] = {file: "MW_AnalogInput_cpp.html",line:31,type:"fcn"};
this.def["MW_AnalogIn_EnableNotification"] = {file: "MW_AnalogInput_cpp.html",line:39,type:"fcn"};
this.def["MW_AnalogIn_DisableNotification"] = {file: "MW_AnalogInput_cpp.html",line:45,type:"fcn"};
this.def["MW_AnalogIn_EnableContConversion"] = {file: "MW_AnalogInput_cpp.html",line:51,type:"fcn"};
this.def["MW_AnalogIn_SetChannelConvRank"] = {file: "MW_AnalogInput_cpp.html",line:57,type:"fcn"};
this.def["MW_AnalogIn_GetStatus"] = {file: "MW_AnalogInput_cpp.html",line:65,type:"fcn"};
this.def["MW_AnalogInSingle_ReadResult"] = {file: "MW_AnalogInput_cpp.html",line:71,type:"fcn"};
this.def["MW_AnalogIn_Start"] = {file: "MW_AnalogInput_cpp.html",line:89,type:"fcn"};
this.def["MW_AnalogIn_Stop"] = {file: "MW_AnalogInput_cpp.html",line:95,type:"fcn"};
this.def["MW_AnalogIn_Close"] = {file: "MW_AnalogInput_cpp.html",line:101,type:"fcn"};
this.def["MW_AnalogIn_GetHandle"] = {file: "MW_AnalogInput_cpp.html",line:106,type:"fcn"};
this.def["MW_Arduino_Init"] = {file: "MW_ArduinoHWInit_cpp.html",line:22,type:"fcn"};
this.def["ret"] = {file: "MW_arduino_digitalio_cpp.html",line:31,type:"var"};
this.def["getLoopbackIP"] = {file: "MW_target_hardware_resources_h.html",line:11,type:"var"};
this.def["oldtime"] = {file: "arduinoAVRScheduler_cpp.html",line:10,type:"var"};
this.def["actualtime"] = {file: "arduinoAVRScheduler_cpp.html",line:11,type:"var"};
this.def["scheduler_counter"] = {file: "arduinoAVRScheduler_cpp.html",line:16,type:"var"};
this.def["scheduler_counter"] = {file: "arduinoAVRScheduler_cpp.html",line:18,type:"var"};
this.def["scheduler_counter"] = {file: "arduinoAVRScheduler_cpp.html",line:20,type:"var"};
this.def["configureArduinoAVRTimer"] = {file: "arduinoAVRScheduler_cpp.html",line:53,type:"fcn"};
this.def["disable_rt_OneStep"] = {file: "arduinoAVRScheduler_cpp.html",line:73,type:"fcn"};
this.def["MW_Arduino_Loop"] = {file: "arduinoAVRScheduler_cpp.html",line:81,type:"fcn"};
this.def["libFcnOutput"] = {file: "io_wrappers_cpp.html",line:61,type:"var"};
this.def["_RTT_UDP_"] = {file: "io_wrappers_cpp.html",line:131,type:"var"};
this.def["mac"] = {file: "io_wrappers_cpp.html",line:133,type:"var"};
this.def["_RTT_UDP_"] = {file: "io_wrappers_cpp.html",line:134,type:"var"};
this.def["configureSuccess"] = {file: "io_wrappers_cpp.html",line:135,type:"var"};
this.def["trialcount"] = {file: "io_wrappers_cpp.html",line:136,type:"var"};
this.def["io_wrappers.cpp:only_one_ethernet_begin"] = {file: "io_wrappers_cpp.html",line:139,type:"var"};
this.def["packetSize"] = {file: "io_wrappers_cpp.html",line:211,type:"var"};
this.def["mac"] = {file: "io_wrappers_cpp.html",line:230,type:"var"};
this.def["configureSuccess"] = {file: "io_wrappers_cpp.html",line:231,type:"var"};
this.def["trialcount"] = {file: "io_wrappers_cpp.html",line:232,type:"var"};
this.def["_RTT_TCP_"] = {file: "io_wrappers_cpp.html",line:234,type:"var"};
this.def["io_wrappers.cpp:only_one_tcp_server_and_ethernet_begin"] = {file: "io_wrappers_cpp.html",line:238,type:"var"};
this.def["libFcnOutput"] = {file: "io_wrappers_cpp.html",line:313,type:"var"};
this.def["client"] = {file: "io_wrappers_cpp.html",line:314,type:"var"};
this.def["start_time"] = {file: "io_wrappers_cpp.html",line:361,type:"var"};
}
CodeDefine.instance = new CodeDefine();
var testHarnessInfo = {OwnerFileName: "", HarnessOwner: "", HarnessName: "", IsTestHarness: "0"};
var relPathToBuildDir = "../ert_main.c";
var fileSep = "\\";
var isPC = true;
function Html2SrcLink() {
	this.html2SrcPath = new Array;
	this.html2Root = new Array;
	this.html2SrcPath["ert_main_c.html"] = "../ert_main.c";
	this.html2Root["ert_main_c.html"] = "ert_main_c.html";
	this.html2SrcPath["ArduinoTest_c.html"] = "../ArduinoTest.c";
	this.html2Root["ArduinoTest_c.html"] = "ArduinoTest_c.html";
	this.html2SrcPath["ArduinoTest_h.html"] = "../ArduinoTest.h";
	this.html2Root["ArduinoTest_h.html"] = "ArduinoTest_h.html";
	this.html2SrcPath["ArduinoTest_private_h.html"] = "../ArduinoTest_private.h";
	this.html2Root["ArduinoTest_private_h.html"] = "ArduinoTest_private_h.html";
	this.html2SrcPath["ArduinoTest_types_h.html"] = "../ArduinoTest_types.h";
	this.html2Root["ArduinoTest_types_h.html"] = "ArduinoTest_types_h.html";
	this.html2SrcPath["ArduinoTest_data_c.html"] = "../ArduinoTest_data.c";
	this.html2Root["ArduinoTest_data_c.html"] = "ArduinoTest_data_c.html";
	this.html2SrcPath["rtwtypes_h.html"] = "../rtwtypes.h";
	this.html2Root["rtwtypes_h.html"] = "rtwtypes_h.html";
	this.html2SrcPath["rtmodel_h.html"] = "../rtmodel.h";
	this.html2Root["rtmodel_h.html"] = "rtmodel_h.html";
	this.html2SrcPath["MW_AnalogIn_h.html"] = "file:///C:/ProgramData/MATLAB/SupportPackages/R2019a/toolbox/target/shared/svd/include/MW_AnalogIn.h";
	this.html2Root["MW_AnalogIn_h.html"] = "MW_AnalogIn_h.html";
	this.html2SrcPath["MW_AnalogInput_cpp.html"] = "file:///C:/ProgramData/MATLAB/SupportPackages/R2019a/toolbox/target/supportpackages/arduinobase/src/MW_AnalogInput.cpp";
	this.html2Root["MW_AnalogInput_cpp.html"] = "MW_AnalogInput_cpp.html";
	this.html2SrcPath["MW_ArduinoHWInit_cpp.html"] = "file:///C:/ProgramData/MATLAB/SupportPackages/R2019a/toolbox/target/supportpackages/arduinotarget/registry/../src/MW_ArduinoHWInit.cpp";
	this.html2Root["MW_ArduinoHWInit_cpp.html"] = "MW_ArduinoHWInit_cpp.html";
	this.html2SrcPath["MW_arduino_digitalio_cpp.html"] = "file:///C:/ProgramData/MATLAB/SupportPackages/R2019a/toolbox/target/supportpackages/arduinobase/src/MW_arduino_digitalio.cpp";
	this.html2Root["MW_arduino_digitalio_cpp.html"] = "MW_arduino_digitalio_cpp.html";
	this.html2SrcPath["MW_arduino_digitalio_h.html"] = "file:///C:/ProgramData/MATLAB/SupportPackages/R2019a/toolbox/target/supportpackages/arduinobase/include/MW_arduino_digitalio.h";
	this.html2Root["MW_arduino_digitalio_h.html"] = "MW_arduino_digitalio_h.html";
	this.html2SrcPath["MW_target_hardware_resources_h.html"] = "../MW_target_hardware_resources.h";
	this.html2Root["MW_target_hardware_resources_h.html"] = "MW_target_hardware_resources_h.html";
	this.html2SrcPath["arduinoAVRScheduler_cpp.html"] = "file:///C:/ProgramData/MATLAB/SupportPackages/R2019a/toolbox/target/supportpackages/arduinotarget/registry/../scheduler/src/arduinoAVRScheduler.cpp";
	this.html2Root["arduinoAVRScheduler_cpp.html"] = "arduinoAVRScheduler_cpp.html";
	this.html2SrcPath["io_wrappers_cpp.html"] = "file:///C:/ProgramData/MATLAB/SupportPackages/R2019a/toolbox/target/supportpackages/arduinobase/src/io_wrappers.cpp";
	this.html2Root["io_wrappers_cpp.html"] = "io_wrappers_cpp.html";
	this.getLink2Src = function (htmlFileName) {
		 if (this.html2SrcPath[htmlFileName])
			 return this.html2SrcPath[htmlFileName];
		 else
			 return null;
	}
	this.getLinkFromRoot = function (htmlFileName) {
		 if (this.html2Root[htmlFileName])
			 return this.html2Root[htmlFileName];
		 else
			 return null;
	}
}
Html2SrcLink.instance = new Html2SrcLink();
var fileList = [
"ert_main_c.html","ArduinoTest_c.html","ArduinoTest_h.html","ArduinoTest_private_h.html","ArduinoTest_types_h.html","ArduinoTest_data_c.html","rtwtypes_h.html","rtmodel_h.html","MW_AnalogIn_h.html","MW_AnalogInput_cpp.html","MW_ArduinoHWInit_cpp.html","MW_arduino_digitalio_cpp.html","MW_arduino_digitalio_h.html","MW_target_hardware_resources_h.html","arduinoAVRScheduler_cpp.html","io_wrappers_cpp.html"];
